
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

var es = {
    
    "{{potencia leida}}": "Pot. Leida",
    "{{potencia valida}}": "Pot. Valida",
    "{{potencia facturar}}": "Pot. Facturar",
    "{{Editar Lectura Pequeña Demanda}}": "Editar Lectura Pequeña Demanda",
    "{{Editar Lectura Mediana Demanda}}": "Editar Lectura Mediana Demanda",
    "{{Editar Lectura Gran Demanda}}": "Editar Lectura Gran Demanda",
    "{{trafo_nro}}": "Nro de Transformador",
    "{{trafo_fecha_alta}}": "Fecha Alta",
    "{{trafo_fecha_baja}}": "Fecha Baja",
    "{{trafo_capacidad}}": "Capacidad",
    "{{trafo_propiedad}}": "Propiedad",
    "{{perdida_cu}}": "Perdida Cobre",
    "{{perdida_fe}}": "Perdida Fierro",
    "{{Transformador}}": "Transformador",
    "{{Consumidor Perdidas Transformador}}": "Consumidor Perdidas Transformador",
    "{{Lista}}": "Lista",
    "{{TrafoNro}}": "TrafoNro",
    "{{Fecha de Alta}}": "Fecha de Alta",
    "{{Fecha de Baja}}": "Fecha de Baja",
    "{{TrafoCapacidad}}": "TrafoCapacidad",
    "{{Propiedad}}": "Propiedad",
    "{{formulario}}": "Formulario",
    "{{Empresa}}": "Empresa",
    "{{Consumidor}}": "Cliente",
    "{{PerididaCu}}": "PerididaCu",
    "{{PerdidaFe}}": "PerdidaFe",
    "{{Codigo Consumidor}}": "Codigo Consumidor",
    "{{i}}": "<span  class='tooltipRequired'><span class='classTooltip' data-toggle='tooltip' data-placement='left' title='{{requiredField}}'>*&nbsp;</span></span>",
    "{{requiredField}}": "Requerido",
    "{{al}}": "al",
    "{{notFoundRows}}": "No se encontraron registros.",
    "{{notFoundRowEnable}}": "Ning&uacute;n dato disponible en esta tabla",
    "{{searchInCurrentView}}": "Buscar en vista actual",
    "{{searchFirst}}": "Realizar b&uacute;squeda para mostrar datos",
    "{{sInfoEmpty}}": "Mostrando registros del 0 al 0 de un total de 0 registros",
    "{{primero}}": "Primero",
    "{{ultimo}}": "&uacute;ltimo",
    "{{siguiente}}": "Siguiente",
    "{{anterior}}": "Anterior",
    "{{sInfo}}": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "{{filtrar}}": "Filtrar",
    "{{por}}": "por",
    "{{archivo}}": "Archivo",
    "{{registrador}}": "Registrador",
    "{{gestion}}": "Gesti&oacute;n",
    "{{de}}": "de",
    "{{eliminar}}": "Eliminar",
    "{{importar}}": "Importar",
    "{{reset}}": "Limpiar",
    "{{buscar}}": "Buscar",
    "{{cerrar}}": "Cerrar",
    "{{guardar}}": "Guardar",
    "{{gestionar}}": "Gestionar",
    "{{crear}}": "Crear",
    "{{editar}}": "Editar",
    "{{clase}}": "Clase",
    "{{clases}}": "Clases",
    "{{codigo}}": "C&oacute;digo",
    "{{descripcion}}": "Descripci&oacute;n",
    "{{modelo}}": "Modelo",
    "{{modelos}}": "Modelos",
    "{{posicion}}": "Posici&oacute;n",
    "{{posiciones}}": "Posiciones",
    "{{serie}}": "Serie",
    "{{series}}": "Series",
    "{{tipo}}": "Tipo",
    "{{tipos}}": "Tipos",
    "{{equipo}}": "Equipo",
    "{{lugar}}": "Lugar",
    "{{equipos}}": "Equipos",
    "{{tarifa}}": "Tarifa",
    "{{base}}": "Base",
    "{{seleccione}}": "-- Seleccione --",
    "{{precinto}}": "Precinto",
    "{{precintos}}": "Precintos",
    "{{codigos}}": "C&oacute;digos",
    "{{color}}": "Color",
    "{{marca}}": "Marca",
    "{{material}}": "Material",
    "{{punto}}": "Punto",
    "{{puntocontrol}}": "Punto Control",
    "{{cronograma}}": "Cronograma",
    "{{medida}}": "Medida",
    "{{instalacion}}": "Instalaci&oacute;n",
    "{{relacion}}": "Relaci&oacute;n",
    "{{norma}}": "Norma",
    "{{regulador}}": "Regulador",
    "{{sorteo}}": "Sorteo",
    "{{bil}}": "BIL (kv)",
    "{{frecuencia}}": "Frecuencia (Hz)",
    "{{voltaje}}": "Voltaje",
    "{{servicio}}": "Servicio",
    "{{precision}}": "Precisi&oacute;n (%)",
    "{{burden_1}}": "Burden (&Omega;): 1)",
    "{{burden_2}}": "Burden (&Omega;): 2)",
    "{{burden_3}}": "Burden (&Omega;): 3)",
    "{{burden}}": "Burden (VA)",
    "{{factorTermico}}": "Factor T&eacute;rmico",
    "{{stdAmb}}": "STC AMB (&deg;C)",
    "{{potenciaTermica}}": "Potencia T&eacute;rmica",
    "{{caracteristicas}}": "Caracter&iacute;sticas",
    "{{asociado}}": "Asociado",
    "{{forma}}": "Forma",
    "{{conexion}}": "Conexi&oacute;n",
    "{{anio}}": "A&ntilde;o",
    "{{fabricacion}}": "Fabricaci&oacute;n",
    "{{pais}}": "Pa&iacute;s",
    "{{origen}}": "Origen",
    "{{tension}}": "Tensi&oacute;n (V)",
    "{{corriente}}": "Corriente (A)",
    "{{numeroFases}}": "Nro. Fases",
    "{{numeroHilos}}": "Nro. Hilos",
    "{{numeroElementos}}": "Nro. Elementos",
    "{{kh}}": "Kh",
    "{{rr}}": "Rr",
    "{{rs}}": "Rs",
    "{{medidor}}": "Medidor",
    "{{medidores}}": "Medidores",
    "{{Si}}": "Si",
    "{{No}}": "No",
    "{{mide}}": "Mide",
    "{{enteros}}": "Enteros",
    "{{decimales}}": "Decimales",
    "{{tope}}": "Tope",
    "{{bloque}}": "Bloque",
    "{{energiaBs}}": "Energ&iacute;a Bs.",
    "{{constante}}": "Constante",
    "{{prueba}}": "Prueba",
    "{{propia}}": "Propia",
    "{{obsoleto}}": "Obsoleto",
    "{{plan}}": "Plan",
    "{{produccion}}": "Producci&oacute;n",
    "{{control}}": "Control",
    "{{precio}}": "Precio",
    "{{mes}}": "Mes",
    "{{remesa}}": "Remesa",
    "{{area}}": "Area",
    "{{estado}}": "Estado",
    "{{generar}}": "Generar",
    "{{consumidores}}": "Consumidores",
    "{{consumidor}}": "Consumidor",
    "{{fecha descarga}}": "Fecha Descarga",
    "{{fecha lectura}}": "Fecha Lectura",
    "{{diferencia}}": "Diferencia",
    "{{lectura generada}}": "Generadas",
    "{{lectura recepcionada}}": "Recibidas",
    "{{lectura enviada}}": "Enviadas",
    "{{lectura recibida}}": "Recibidas",
    "{{rutaTrabajar}}": "Trabajar con Ruta",
    "{{cantidad}}": "Cantidad",
    "{{inicial}}": "Inicial",
    "{{final}}": "Final",
    "{{alta}}": "Alta",
    "{{baja}}": "Baja",
    "{{masiva}}": "Masiva",
    "{{individual}}": "Individual",
    "{{historial}}": "Historial",
    "{{lista}}": "Lista",
    "{{Nombre Completo}}": "Nombre Completo",
    "{{Direccion}}": "Direcci&oacute;n",
    "{{Estado}}": "Estado",
    "{{Cod. Consumidor}}": "Cod. Consumidor",
    "{{Interes}}": "Inter&eacute;s",
    "{{Fecha vencimiento}}": "Fecha vencimiento",
    "{{Aseo}}": "Aseo",
    "{{Alumbrado}}": "Alumbrado",
    "{{AlumbradoBs}}": "Alumbrado Bs.",
    "{{Total}}": "Total",
    "{{Anadir Cobro}}": "Añadir Cobro",
    "{{Ci}}": "Ci",
    "{{cancelar}}": "Cancelar",
    "{{Cobrar}}": "Cobrar",
    "{{Recibido}}": "Recibido",
    "{{Cambio}}": "Cambio",
    "{{Energia}}": "Energ&iacute;a",
    "{{Cobro en efectivo}}": "Cobro en efectivo",
    "{{Detalle}}": "Detalle",
    "{{Cobrar en}}": "Cobrar en",
    "{{Filtrar por}}": "Filtrar por",
    "{{factura}}": "Factura",
    "{{Impresion}}": "Impresi&oacute;n",
    "{{Imprimir}}": "Imprimir",
    "{{motivo}}": "Motivo",
    "{{conclucion}}": "Conclusi&oacute;n",
    "{{observaciones}}": "Observaciones",
    "{{masivamente}}": "Masivamente",
    "{{Cobro en cheque}}": "Cobro en cheque",
    "{{Entidad financiera}}": "Entidad financiera",
    "{{Nro. Cuenta banco origen}}": "Nro. Cuenta banco origen",
    "{{Nro. Doc. (cheque)}}": "Nro. Doc. (cheque)",
    "{{Importe}}": "Importe",
    "{{Fecha cheque}}": "Fecha cheque",
    "{{multiplicador}}": "Mult.",
    "{{fecha}}": "Fecha",
    "{{hora}}": "Hora",
    "{{nombre}}": "Nombre",
    "{{direccion}}": "Direcci&oacute;n",
    "{{consumo promedio}}": "Promedio",
    "{{lectura actual}}": "Lectura Actual",
    "{{lectura anterior}}": "Lectura Anterior",
    "{{consumo actual}}": "Consumo",
    "{{observacion}}": "Observacion",
    "{{Impresion de cobro}}": "Impresi&oacute;n de cobro",
    "{{cobro}}": "cobro",
    "{{acciones}}": "Acciones",
    "{{Tipo de pago}}": "Tipo de pago",
    "{{ordenes}}": "Ordenes",
    "{{setor}}": "Sector",
    "{{orden}}": "Orden",
    "{{solicitud}}": "Solicitud",
    "{{numero}}": "N&uacute;mero",
    "{{empresa}}": "Empresa",
    "{{propiedad}}": "Propiedad",
    "{{a}}": "A",
    "{{ser}}": "Ser",
    "{{asignado}}": "Asignado",
    "{{en}}": "En",
    "{{fabrica}}": "F&aacute;brica",
    "{{contrastacion}}": "Contrastaci&oacute;n",
    "{{precintado}}": "Precintado",
    "{{asignar}}": "Asignar",
    "{{multiplicacion}}": "Multiplicaci&oacute;n",
    "{{asignacion}}": "Asignaci&oacute;n",
    "{{SS}}": "S/S",
    "{{ver}}": "Ver",
    "{{numeroSolicitud}}": "N&uacute;mero Solicitud",
    "{{nombres}}": "Nombres",
    "{{numeroConsumidor}}": "N&uacutemero Consumidor",
    "{{CI}}": "CI",
    "{{apellidoPaterno}}": "Apellido Paterno",
    "{{apellidoMaterno}}": "Apellido Materno",
    "{{tipoSolicitud}}": "Tipo Solicitud",
    "{{fechaActualizacion}}": "Fecha actualizaci&oacute;n",
    "{{emitirOrdenInspeccion}}": "Emitir Inspecci&oacute;n",
    "{{emitirDebitos}}": "Emitir Debitos",
    "{{generarContrato}}": "Generar Contrato",
    "{{confirmEmitirInsepccion}}": "Esta seguro de emitir la orden de inspecci&oacute;n?",
    "{{confirmEmitirDebitos}}": "Esta seguro de emitir los debtios?",
    "{{confirmGenerarContrato}}": "Esta seguro de generar contrato?",
    "{{generearDebitos}}": "Generar Debitos",
    "{{emitirTiposDebitos}}": "Emitir tipos de debitos",
    "{{confirmar}}": "Confirmar",
    "{{areaLocalidad}}": "Area/Localidad",
    "{{juridico}}": "Jur&iacute;dico",
    "{{solicitadoPor}}": "Solicitado por",
    "{{email}}": "E-mail",
    "{{genero}}": "G&eacutenero",
    "{{estadoCivil}}": "Estado Civil",
    "{{tipoDocumento}}": "Tipo Documento",
    "{{documento}}": "Documento",
    "{{nit}}": "NIT",
    "{{razonSocial}}": "Raz&oacute;n Social",
    "{{fechaNacimiento}}": "Fecha Nacimiento",
    "{{telefonos}}": "Tel&eacutefonos",
    "{{barrio}}": "Barrio",
    "{{zona}}": "Zona",
    "{{numeroVivienda}}": "Nro. Vivienda",
    "{{pisoDepartamento}}": "Piso Departamento",
    "{{numeroDepartamento}}": "Nro. Departamento",
    "{{actividadEconomica}}": "Actividad econ&oacute;mica",
    "{{generarSolicitud}}": "Generar Solicitud",
    "{{tipoSistema}}": "Tipo Sistema",
    "{{condicion}}": "Condici&oacute;n",
    "{{cartaFactura}}": "Carta Factura",
    "{{medidorReferencia}}": "Medidor De Referencia",
    "{{medidorReferenciaPosicion}}": "Posici&oacute;n Medidor Ref.",
    "{{propiedadMedidorEmpresa}}": "Propiedad Med. (Empresa)",
    "{{fechaEstimadaInspeccion}}": "Fecha Estimada Inspecci&oacute;n",
    "{{datosPersona}}": "Datos Persona",
    "{{datosDireccion}}": "Datos Direcci&oacute;n",
    "{{datosServicio}}": "Datos Servicio",
    "{{otrosDatos}}": "Datos Adicionales",
    "{{codigoOrden}}": "C&oacute;digo Orden",
    "{{codigoSolicitud}}": "C&oacute;digo Solicitud",
    "{{fechaInicio}}": "F. Ini",
    "{{fechaFin}}": "F. Fin",
    "{{ejecutar}}": "Ejecutar",
    "{{datosInspeccion}}": "Datos Inspecci&oacute;n",
    "{{datosTarifa}}": "Datos Tarifa",
    "{{fechaRealInspeccion}}": "Fecha Real Inspecci&oacute;n",
    "{{resultado}}": "Resultado",
    "{{responsableCasa}}": "Responsable de casa",
    "{{observacionInspeccion}}": "Observaciones Inspecci&oacute;n",
    "{{inspeccion}}": "Inspecci&oacute;n",
    "{{direccionMedidorReferencia}}": "Direcci&oacute;n Med. Referencia",
    "{{potInstKw}}": "Potencia Instalada",
    "{{nivelDemanda}}": "Nivel Demanda",
    "{{voltajeAsignado}}": "Voltaje Asignado",
    "{{descrptarifa}}": "Descripci&oacute;n Tarifa",
    "{{potDemandaKw}}": "Potencia Demandada kW",
    "{{ptoSuministro}}": "Punto Suministro",
    "{{sistemaMedicion}}": "Sistema Medici&oacute;n",
    "{{ptoMedicion}}": "Punto Medici&oacute;n",
    "{{potPuntaDeclaradaKw}}": "Potencia de punta Declarada kW",
    "{{potMaxDeclaradaKw}}": "Potencia M&aacute;xima Declarada kW",
    "{{voltajeRed}}": "Voltaje Red",
    "{{codCartografico}}": "C&oacute;digo Cartografico",
    "{{nroProyecto}}": "N&uacute;mero Proyecto",
    "{{numeroMedidor}}": "N&uacute;mero medidor",
    "{{numeroFabrica}}": "N&uacute;mero F&aacute;brica",
    "{{puntoMedida}}": "Punto Medida",
    "{{tipoConexi&oacute;n}}": "Tipo Conexi&oacute;n",
    "{{voltajeAsociado}}": "Voltaje Asociado",
    "{{buscarMedidor}}": "Buscar Medidor",
    "{{artefactos}}": "Artefactos",
    "{{artefacto}}": "Artefacto",
    "{{uVatio}}": "Unidad/Watts",
    "{{totalVatios}}": "Total Watts",
    "{{facturador}}": "Facturador",
    "{{procesofacturacion}}": "Proceso de Facturaci&oacute;n",
    "{{Banco}}": "Banco",
    "{{Correo electronico}}": "Correo electr&oacute;nico",
    "{{Responsable}}": "Responsable",
    "{{Cuenta}}": "Cuenta",
    "{{FechaDeRegistro}}": "Fecha de registro",
    "{{Descripcion}}": "Descripci&oacute;n",
    "{{Correo}}": "Correo",
    "{{Agencia}}": "Agencia",
    "{{Tipo}}": "Tipo",
    "{{Fecha registro}}": "Fecha registro",
    "{{reImprimirInspeccion}}": "Re-imprimir Inspecci&oacute;n",
    "{{motivos}}": "Motivos",
    "{{concluciones}}": "Conclusiones",
    "{{todos}}": "Todos",
    "{{fechalecturahabilitacion}}": "Fecha Lectura Habilitaci&oacute;n",
    "{{fechalecturareal}}": "Fecha_de   Lectura  Real",
    "{{fechacorte}}": "Fecha_de Corte",
    "{{edicion}}": "Edici&oacute;n",
    "{{remesaCodigo}}": "Remesa C&oacute;digo",
    "{{fechaLecturaDescarga}}": "Fecha Lectura Descarga",
    "{{fechaLecturaValidacion}}": "Fecha Lectura Validaci&oacute;n",
    "{{fechaEmisionFactura}}": "Fecha Emisi&oacute;n Factura",
    "{{fechaPrimerVencimiento}}": "Fecha 1er Vencimiento",
    "{{fechaSegundoVencimiento}}": "Fecha 2do Vencimiento",
    "{{procedimiento}}": "Procedimiento",
    "{{procedimientos}}": "Procedimientos",
    "{{valor}}": "Valor",
    "{{activo}}": "Activo",
    "{{estado_activo}}": "Activo",
    "{{estado_inactivo}}": "Inactivo",
    "{{patron}}": "Patr&oacute;n",
    "{{patrones}}": "Patrones",
    "{{certificado}}": "Certificado",
    "{{trazabilidad}}": "Trazabilidad",
    "{{incertidumbre}}": "Incertidumbre",
    "{{tap}}": "Tap",
    "{{utilizado}}": "Utilizado",
    "{{correccion}}": "Correcci&oacute;n",
    "{{inductiva}}": "Inductiva",
    "{{sigla}}": "Sigla",
    "{{indice}}": "Indice",
    "{{t1}}": "L1-L2",
    "{{t2}}": "L2-L3",
    "{{t3}}": "L3-L1",
    "{{potencia}}": "Potencia",
    "{{inicio}}": "Inicio",
    "{{periodo}}": "Periodo",
    "{{separador}}": "Separador",
    "{{configuracion}}": "Configuraci&oacute;n",
    "{{agregar_programa}}": "Agregar Configuraci&oacute;n",
    "{{eliminar_programa}}": "Eliminar Configuraci&oacute;n",
    "{{modificar_programa}}": "Modificar Configuraci&oacute;n",
    "{{upotencia}}": "Unidad/Potencia",
    "{{unidad}}": "Unidad",
    "{{unidades}}": "Unidades",
    "{{medidas}}": "Medidas",
    "{{calidad}}": "Calidad",
    "{{maximo}}": "M&aacute;ximo",
    "{{minimo}}": "M&iacute;nimo",
    "{{limite}}": "L&iacute;mite",
    "{{campana}}": "Campa&ntilde;a",
    "{{tipoReclamo}}": "Tipo Reclamo",
    "{{tipoDeReclamo}}": "Tipo de Reclamo",
    "{{CanalDiario}}": "Canal Diario",
    "{{CanalDiarioConsulta}}": "Canal Diario Consulta",
    "{{Sistema}}": "Sistema",
    "{{etapa}}": "Etapa",
    "{{tipo falla}}": "Tipo Falla",
    "{{cod protec}}": "Cod_Protec",
    "{{cod alim}}": "Cod Alim",
    "{{cod origen}}": "Cod Origen",
    "{{cod causa}}": "Cod Causa",
    "{{fecha_i}}": "Fecha Inicial ",
    "{{fecha_f}}": "Fecha Final",
    "{{hora ini}}": "Hora Inicial",
    "{{hora fin}}": "Hora Final",
    "{{tiempo}}": "Tiempo",
    "{{num consum 1}}": "Num Consum 1",
    "{{num consum 2}}": "Num Consum 2",
    "{{trabajo realizado}}": "Trabajo Realizado",
    "{{total repos}}": "Total Repos",
    "{{canalmensual}}": "Canal Mensual",
    "{{generarcanalmensual}}": "Generar Canal Mensual",
    "{{medidorDeReferencia}}": "Med. Ref.",
    "{{parametros texto}}": "Parametros Textos",
    "{{solicitudes}}": "Solicitudes",
    "{{sector}}": "Sector",
    "{{telefono}}": "Tel&eacute;fono",
    "{{numeroCasa}}": "Nro. Casa",
    "{{numeroDocumento}}": "Nro. Documento",
    "{{seleccionar}}": "Seleccionar",
    "{{detalle}}": "Detalle",
    "{{datosOS}}": "Datos O/S",
    "{{numReclamo}}": "Nro. Reclamo",
    "{{numMedidor}}": "Nro. Medidor",
    "{{numConsumidor}}": "Nro. Consumidor",
    "{{numSolicitud}}": "Nro. Solicitud",
    "{{demanda}}": "Demanda",
    "{{tipoRecepcion}}": "Tipo Recepcion",
    "{{tipoDeRecepcion}}": "Tipo de Recepci&oacute;n",
    "{{titular}}": "Titular",
    "{{tercero}}": "Tercero",
    "{{requisitos}}": "Lista requisitos",
    "{{reImprimirSolicitud}}": "Re-imprimir solicitud",
    "{{reImpresionSolicitud}}": "Re-impresi&0acute;n solicitud",
    "{{tipoOrden}}": "Tipo Orden",
    "{{ordenesSugeridas}}": "Ordenes sugeridas",
    "{{recParentesco}}": "Parentesco",
    "{{datosConexion}}": "Datos conexi&oacute;n",
    "{{datosAdicionales}}": "Datos adicionales",
    "{{resultadoDelTrabajo}}": "Resultado del trabajo",
    "{{codigoConsumidor}}": "C&oacute;digo consumidor",
    "{{fechaCumplimiento}}": "Fecha cumplimiento",
    "{{operador}}": "Operador",
    "{{forzada}}": "Forzada",
    "{{observacionesdecumplimiento}}": "Observaciones de cumplimiento",
    "{{codigomedidor}}": "C&oacute;digo Medidor",
    "{{poste}}": "Poste",
    "{{puesto}}": "Puesto",
    "{{sectordestino}}": "Sector de destino",
    "{{cumplimientoOrdenServicio}}": "Cumplimiento de Orden de Servicio",
    "{{horaCumplimiento}}": "Hora de cumplimiento",
    "{{tipoDeTrabajo}}": "Tipo de trabajo",
    "{{motivoDeDemora}}": "Motivo de demora",
    "{{ultimoIndiceEnergia}}": "Ultimo &iacute;ndice de energ&iacute;a",
    "{{tipoDeMedidor}}": "Tipo de medidor",
    "{{indiceDeEnergia}}": "Indice de energ&iacute;a",
    "{{cumplimientoOrden}}": "Cumplimiento de Orden",
    "{{datosDesconexion}}": "Datos de Desconexi&oacute;n",
    "{{NroConsumidor}}": "Nro Consumidor",
    "{{NroSolicitud}}": "Nro Solicitud",
    "{{ordenesGenerales}}": "Ordenes Generales",
    "{{cortesYsuspensiones}}": "Cortes y suspensiones",
    "{{fechaMin}}": "Fecha min.",
    "{{fechaMax}}": "Fecha max.",
    "{{corte}}": "Corte",
    "{{suspension}}": "Suspensi&oacute;n",
    "{{sectorOrigen}}": "Sector or&iacute;gen",
    "{{sectorDestino}}": "Sector destino",
    "{{sectorConsumidorEspecial}}": "Sector consumidor especial",
    "{{montoMinimo}}": "Monto m&iacute;nimo",
    "{{diasHolgura}}": "D&iacute;as holgura",
    "{{estadoServicioDesde}}": "Estado servicio desde",
    "{{montoMaximo}}": "Monto m&aacute;ximo",
    "{{cantidadAgenerar}}": "Cantidad a generar",
    "{{estadoServicioHasta}}": "Estado servicio hasta",
    "{{porAreaRemesaRuta}}": "Por &aacute;rea remesa ruta",
    "{{porCategoria}}": "Por categor&iacute;a",
    "{{remesaDesde}}": "Remesa desde",
    "{{remesaHasta}}": "Remesa hasta",
    "{{rutaDesde}}": "Ruta desde",
    "{{rutaHasta}}": "Ruta hasta",
    "{{categoriaDesde}}": "Categor&iacute;a desde",
    "{{categoriaHasta}}": "Categor&iacute;a hasta",
    "{{categoriaNotificacion}}": "Categor&iacute;as Notificaci&oacute;n",
    "{{categoriaDeNotificacion}}": "Categor&iacute;as de Notificaci&oacute;n",
    "{{idCategoriaNotificacion}}": "Categor&iacute;a",
    "{{tipoNotificacion}}": "Tipo Notificaci&oacute;n",
    "{{tipoDeNotificacion}}": "Tipo de Notificaci&oacute;n",
    "{{numDocumento}}": "Nro Documento",
    "{{generarInspeccion}}": "Generar Inspecci&oacute;n",
    "{{crearTipoSolicitud}}": "Crear Tipo de Solicitud",
    "{{pronunciamiento}}": "Pronunciamiento",
    "{{reclamo}}": "Reclamo",
    "{{entre}}": "Entre",
    "{{numeroReclamo}}": "N&uacute;mero reclamo",
    "{{listado}}": "Listado",
    "{{fechaHecho}}": "Fecha hecho",
    "{{nroMedidor}}": "Medidor",
    "{{codigoReclamo}}": "C&oacute;digo reclamo",
    "{{codigoDeReclamo}}": "C&oacute;digo de Reclamo",
    "{{motivoDemora}}": "Motivo demora",
    "{{respuesta}}": "Respuesta",
    "{{causa}}": "Causa",
    "{{causaInterna}}": "Causa Interna",
    "{{despachante}}": "Despachante",
    "{{recepcion}}": "Recepci&oacute;n",
    "{{retiro}}": "Retiro",
    "{{notificacion}}": "Notificaci&oacute;n",
    "{{fechaEstimadaResultado}}": "Fecha estimada de resultado",
    "{{comunicacion}}": "Comunicaci&oacute;n",
    "{{parentesco}}": "Parentesco",
    "{{historicoLlamadasRealizadas}}": "Hist&oacute;rico de llamadas realizadas",
    "{{del}}": "del",
    "{{hecho}}": "hecho",
    "{{piso}}": "Piso",
    "{{departamento}}": "Departamento",
    "{{referencia}}": "Referencia",
    "{{noEsConsumidor}}": "No es consumidor",
    "{{buscarConsumidor}}": "Buscar consumidor",
    "{{seleccioneTipoSolicitud}}": "Debe seleccionar un tipo solicitud",
    "{{tipoSolicitante}}": "Tipo Solicitante",
    "{{eliminarConfirm}}": "Eliminar Dato",
    "{{nombreCompleto}}": "Nombre Completo",
    "{{fechaRecepcion}}": "Fecha recepci&oacute;n",
    "{{cantidadEstimada}}": "Cantidad estimada",
    "{{informacionsemestral}}": "Informaci&oacute;n Semestral",
    "{{nivelcalidad}}": "Nivel Calidad",
    "{{niveltension}}": "Nivel Tensi&oacute;n",
    "{{generarCanalMensual}}": "Genera Canal Mensual",
    "{{verCanalMensualBaseDatos}}": "Detalle del Canal Mensual Base Datos",
    "{{verCanalMensualInterrupciones}}": "Detalle del Canal Mensual Interrupciones",
    "{{descargarCanalMensual}}": "Descargar Canal Mensual (mdb)",
    "{{opcion}}": "Descargar en mdb",
    "{{canalmensualBD}}": "Canal Mensual BD",
    "{{parametro}}": "Par&aacute;metro",
    "{{distribuidor}}": "Distribuidor",
    "{{numerocaso}}": "Num. Caso",
    "{{instalacionesafectadas}}": "Instalaciones afectadas",
    "{{totalconsumidores}}": "Total Coms.",
    "{{fotografias}}": "Fotos",
    "{{actas}}": "Actas",
    "{{formularios}}": "Formularios",
    "{{otros}}": "Otros",
    "{{causainvocada}}": "Causa Invocada",
    "{{descripcioncausa}}": "Desc. Causa",
    "{{seleccioneTipoSolicitante}}": "Debe seleccionar un tipo de solicitante",
    "{{ensayo}}": "Ensayo",
    "{{masivo}}": "Masivo",
    "{{transferencia}}": "Transferencia",
    "{{transferencias}}": "Transferencias",
    "{{envia}}": "Envia",
    "{{recibe}}": "Recibe",
    "{{transferir}}": "Transferir",
    "{{recepcionar}}": "Recepcionar",
    "{{resultados}}": "Resultados",
    "{{cobroConsumidor}}": "Cobro consumidor",
    "{{cobroEn}}": "Cobro en",
    "{{efectivo}}": "Efectivo",
    "{{cod.Consumidor}}": "Cod. Consumidor",
    "{{fechaVencimiento}}": "Fecha vencimiento",
    "{{aseo}}": "Aseo",
    "{{aseoBs}}": "Aseo Bs.",
    "{{alumbradoBs}}": "Alumbrado Bs.",
    "{{total}}": "Total",
    "{{totalBs}}": "Total Bs.",
    "{{anadirCobro}}": "A&ntilde;adir cobro",
    "{{ci}}": "CI",
    "{{impresion}}": "Impresi&oacute;n",
    "{{imprimir}}": "Imprimir",
    "{{refrenda}}": "Refrenda",
    "{{recibo}}": "Recibo",
    "{{generarImpresion}}": "Generar impresi&oacute;n",
    "{{impresionDeCobro}}": "Impresi&oacute;n de cobro",
    "{{formularioDePago}}": "Formulario de pago",
    "{{pagoEnEfectivo}}": "Pago en efectivo",
    "{{recibido}}": "Recibido",
    "{{cambio}}": "Cambio",
    "{{totalACancelar}}": "Total a cancelar",
    "{{importeCancelado}}": "Importe cancelado",
    "{{cheque}}": "Cheque",
    "{{pagoEnCheque}}": "Pago en cheque",
    "{{moneda}}": "Moneda",
    "{{AniadirCheque}}": "Aniadir cheque",
    "{{entidadFinanciera}}": "Entidad financiera",
    "{{nro.CuentaBancoOrigen}}": "Nro. Cuenta banco origen",
    "{{fechaCheque}}": "Fecha cheque",
    "{{documentoDePago}}": "Documento de pago",
    "{{montoDelChequeBs}}": "Monto del cheque Bs.",
    "{{numeroCorrelativo}}": "N&uacute;mero Correlativo",
    "{{codigoReferencia}}": "C&oacute;digo de Referencia",
    "{{montoCancelado}}": "Monto cancelado",
    "{{montoFacturadoBs}}": "Monto Facturado Bs.",
    "{{pagadoBs}}": "Pagado Bs.",
    "{{reImpresion}}": "Re-Impresi&oacute;n",
    "{{filtrarPor}}": "Filtrar por",
    "{{anulacionDeCobranza}}": "Anulaci&oacute;n de cobranza",
    "{{cajero}}": "Cajero",
    "{{n.Recibo}}": "N. Recibo",
    "{{fechaDeRegistro}}": "Fecha de registro",
    "{{imp.Cancelado}}": "Imp. Cancelado",
    "{{consumo actual ba}}": "Cons. Actual Blq. Alto",
    "{{consump actual bm}}": "Cons. Actual Blq. Medio",
    "{{consumo actual reactiva}}": "Cons. Reactivo",
    "{{potencia ba}}": "Pot. Blq. Alto",
    "{{potencia bm}}": "Pot. Blq. Medio",
    "{{potencia bb}}": "Pot. Blq. Bajo",
    "{{exceso fuera punta}}": "Exceso Fuera Punta",
    "{{consumo actual bb}}": "Cons. Actual Blq. Bajo",
    "{{lectura actual reactiva}}": "Lec. Act. Reactiva",
    "{{derivacionDeReclamos}}": "Derivaci&oacute;n de Reclamos",
    "{{asignarAOperador}}": "Asignar a Operador",
    "{{atenderDerivacion}}": "Atender Derivaci&oacute;n",
    "{{remesaEmision}}": "Remesa de emisi&oacute;n",
    "{{reclamante}}": "Reclamante",
    "{{medioRecepcion}}": "Medio de recepci&oacute;n",
    "{{sectorDerivado}}": "Sector derivado",
    "{{fechaDerivacion}}": "Fecha de ferivaci&oacute;n",
    "{{fechaInforme}}": "Fecha de Informe",
    "{{respuestaReclamo}}": "Respuesta de reclamo",
    "{{medidoRespuesta}}": "Medio de respuesta",
    "{{operadorRespuesta}}": "Operador de respuesta",
    "{{notificado}}": "Notificado",
    "{{personaRespuesta}}": "Persona de respuesta",
    "{{fechaLlamada}}": "Fecha de llamada",
    "{{operadorLlamada}}": "Operador de la llamada",
    "{{agencia}}": "Agencia",
    "{{fax}}": "Fax",
    "{{indices}}": "Indices",
    "{{usuarioRegistro}}": "Registro de usuario",
    "{{usuarioActualizacion}}": "Actualizacion de usuario",
    "{{celular}}": "Celular",
    "{{generarValidez}}": "Generar Validez",
    "{{aprobar}}": "Aprobar",
    "{{ciExpedido}}": "Expedici&oacute;n",
    "{{tipo de lectura}}": "Tipo Lectura",
    "{{Razon Social}}": "Razon Social",
    "{{Tipo Lectura}}": "Tipo Lectura",
    "{{descripcion lectura}}": "Descripcion Lectura",
    "{{generarLectura}}": "Generar Lecturas",
    "{{lectura anterior ba}}": "Lec. Ant. ba",
    "{{lectura anterior bm}}": "Lec. Ant. bm",
    "{{lectura anterior bb}}": "Lec. Ant. bb",
    "{{lectura anterior reactiva}}": "Lec. Ant. Reactiva",
    "{{lectura actual ba}}": "Lec. Act. Ba",
    "{{lectura actual bm}}": "Lec. Act. Bm",
    "{{lectura actual bb}}": "Lec. Act. Bb",
    "{{modificar}}": "Modificar",
    "{{inspector}}": "Inspector",
    "{{numeroOrden}}": "N&uacute;mero orden",
    "{{requisito}}": "Requisito",
    "{{subir}}": "Subir Archivo",
    "{{descargar}}": "Descargar Archivo",
    "{{Total Enviados}}": "Generados",
    "{{Total Recibidos}}": "Corregidos",
    "{{categoria}}": "Categoria",
    "{{lectua anterior}}": "Lec. Ant.",
    "{{lectua actual}}": "Lec. Act.",
    "{{consumo}}": "Consumo",
    "{{tipo validez}}": "Tipo",
    "{{aprobar val}}": "Aprobar Validez",
    "{{fechaRegistro}}": "Fecha registro",
    "{{datoslectura}}": "Datos de Lectura",
    "{{historicos}}": "Hist&oacute;ricos",
    "{{datoslecturaG}}": "Datos Lectura Gran Demanda",
    "{{anticipo}}": "Anticipo",
    "{{pagoAnticipado}}": "Pago anticipado",
    "{{fechaIntento}}": "Fecha intento",
    "{{registrarIntento}}": "Registrar intento",
    "{{finalizar}}": "Finalizar",
    "{{comunicar}}": "Comunicar",
    "{{confirmReactivarSolicitud}}": "Esta seguro de reactivar la solicitud",
    "{{confirmReanudarSolicitud}}": "Esta seguro de reanudar la solicitud",
    "{{confirmReactivarInspeccion}}": "Esta seguro de reactivar la solicitud",
    "{{procedente}}": "Procente",
    "{{improcedente}}": "Improcedente",
    "{{codigoRuta}}": "Ruta",
    "{{anadirCheque}}": "A&ntilde;adir Cheque",
    "{{efectivoAnticipo}}": "Efectivo anticipo",
    "{{chequeAnticipo}}": "Cheque anticipo",
    "{{inspeccionReclamos}}": "Inspecci&oacute;n Reclamos",
    "{{derivaciones}}": "Derivaciones",
    "{{informe}}": "Informe",
    "{{personaContacto}}": "Persona de contacto",
    "{{incluirDocumentos}}": "Incluir Documentos",
    "{{fechaInspeccion}}": "Fecha Inspeccion",
    "{{reclamos}}": "Reclamos",
    "{{pronunciarReclamo}}": "Pronunciar Reclamo",
    "{{derivarReclamo}}": "Derivar Reclamo",
    "{{derivar}}": "Derivar",
    "{{nroCod}}": "Nro Codigo",
    "{{tipoVal}}": "Tipo Valor",
    "{{mult}}": "Multiplicador",
    "{{consProm}}": "Cons. Promedio",
    "{{marcaMed}}": "Marca Medidor",
    "{{crearNuevoInsEstado}}": "Nuevo Estado Instalaci&oacute;n",
    "{{editarInsEstado}}": "Editar Estado Instalaci&oacute;n",
    "{{atencion}}": "Atenci&oacute;n",
    "{{tiempoEmpresa}}": "Tiempo Empresa",
    "{{descLec}}": "Desc Lectura",
    "{{SiglaLectura}}": "Sigla Lectura",
    "{{crearNuevoEstado}}": "Crear Estado",
    "{{editarEstado}}": "Editar Estado",
    "{{dav}}": "DAV",
    "{{cobroMultiple}}": "Cobro multiple",
    "{{nro.Doc. cheque}}": "Nro. Doc. Cheque",
    "{{insTipoInforme}}": "Tipo Informe Instalaci&oacute;n",
    "{{informeDefecto}}": "Informe Defecto",
    "{{ordEstado}}": "Estado Orden",
    "{{reanudarSolicitud}}": "Reanudar Solicitud",
    "{{reactivarSolicitud}}": "Reactivar Solicitud",
    "{{reactivarInspeccion}}": "Reactivar Inspecci&oacute;n",
    "{{ordInforme}}": "Informe Orden",
    "{{tipoTrabajo}}": "Tipo Trabajo",
    "{{resultadoTrabajo}}": "Resultado Trabajo",
    "{{pronunciar}}": "Pronunciar",
    "{{artefactosQuemados}}": "Artefactos Quemados",
    "{{codigoArtefacto}}": "Codigo artefacto",
    "{{descripcionArtefacto}}": "Descripcion del artefacto",
    "{{artefactoQuemado}}": "Artefacto Quemado",
    "{{ordTipoOrden}}": "Tipo Orden",
    "{{tipoServicio}}": "Tipo Servicio",
    "{{asignaMedidor}}": "Asigna Medidor",
    "{{desdeOrdenes}}": "Desde &Oacute;rdenes",
    "{{escritorio}}": "Escritorio",
    "{{retiraMedidor}}": "Retira Medidor",
    "{{validaRutaCritica}}": "V&aacute;lida Ruta Cr&iacute;tica",
    "{{laboralAdministrativo}}": "Laboral Administrativo",
    "{{calendario}}": "Calendario",
    "{{laboral}}": "Laboral",
    "{{tipoDia}}": "Tipo D&iacute;a",
    "{{estServCump}}": "Estado Servicio Cumplido",
    "{{estadoServicio}}": "Estado Servicio",
    "{{applySolicitud}}": "Esta seguro de aplicar la solictud",
    "{{Llenado Validez}}": "LLenado Validez",
    "{{ordTipoOrdenInforme}}": "Tipo Orden e Informe",
    "{{solTipoSolicitudRequisito}}": "Tipo Solicitud Requisito",
    "{{Faltan Corregir}}": "Faltan Corregir",
    "{{lugar factura}}": "Lugar",
    "{{aplicarSolicitud}}": "Aplicar Solicitud",
    "{{informacion}}": "Informaci&oacute;n",
    "{{registro}}": "Registro",
    "{{actualizacion}}": "Actualizaci&oacute;n",
    "{{resolucion}}": "Resoluci&oacute;n",
    "{{editarSistemaMayor}}": "Editar Sistema Mayor",
    "{{editarSistemasNuevos}}": "Editar Sistemas Nuevos",
    "{{cambiar}}": "Cambiar",
    "{{facturas}}": "Facturas",
    "{{calcular}}": "Calcular",
    "{{estructura}}": "Estructura",
    "{{FactorIndexacion}}": "Factor Indexaci&oacute;n",
    "{{importe}}": "Importe",
    "{{importeBs}}": "importe Bs.",
    "{{itemFacturacion}}": "Item Facturaci&oacute;n",
    "{{csv}}": "CSV",
    "{{porcentaje}}": "Porcentaje",
    "{{porcentajebajo}}": "Porcentaje Bajo",
    "{{porcentajemedio}}": "Porcentaje Medio",
    "{{porcentajealto}}": "Porcentaje Alto",
    "{{factorcarga}}": "Factor Carga",
    "{{usuario}}": "Usuario",
    "{{aprobarRemesa}}": "Aprobar Lecturas",
    "{{lectura validada}}": "Lectura Validada",
    "{{consumo validado}}": "Consumo Validada",
    "{{codigo observacion}}": "Codigo Observacion",
    "{{descripcion observacion}}": "Descripci&oacute;n Observaci&oacute;n",
    "{{sigla observacion}}": "Sigla Observacion",
    "{{lee}}": "Lee",
    "{{concepto}}": "Concepto",
    "{{localidad}}": "Localidad",
    "{{defecto}}": "Defecto",
    "{{solTipoSolicitudOrden}}": "Tipo Solicitud Orden",
    "{{Apertura}}": "Apertura",
    "{{Cierre}}": "Cierre",
    "{{reaperturar}}": "reaperturar",
    "{{Cuadre Caja}}": "Cierre Caja",
    "{{Efectivo}}": "Efectivo",
    "{{Contable}}": "Contable",
    "{{Diferencia}}": "Diferencia",
    "{{Doc}}": "Doc",
    "{{Cobrados}}": "Cobrados",
    "{{Bs}}": "Bs.",
    "{{Cheque}}": "Cheque",
    "{{sus}}": "$us.",
    "{{Otros Valores}}": "Otros Valores",
    "{{texto}}": "Texto",
    "{{nombreOrs}}": "Nombre o Raz&oacute;n Social",
    "{{telefonoOcelular}}": "Tel&eacute;fono o Celular",
    "{{nroDocumento}}": "N&uacute;mero Documento",
    "{{expedido}}": "Expedido",
    "{{nroFactura}}": "N&uacute;mero Factura",
    "{{nroAutorizacion}}": "N&uacute;mero Autorizaci&oacute;n",
    "{{fechaEmision}}": "Fecha Emisi&oacute;n",
    "{{fechaActual}}": "Fecha Actual",
    "{{credito}}": "Cr&eacute;dito",
    "{{debito}}": "D&eacute;bito",
    "{{datos}}": "Datos",
    "{{consumos}}": "Consumos",
    "{{importes}}": "Importes",
    "{{refacturacion}}": "Refacturaci&oacute;n",
    "{{ajusteImporte}}": "Ajuste Importe",
    "{{bloqueAlto}}": "Bloque Alto",
    "{{bloqueMedio}}": "Bloque Medio",
    "{{bloqueBajo}}": "Bloque Bajo",
    "{{excesoPotencia}}": "Exceso Potencia",
    "{{actual}}": "Actual",
    "{{facturaActual}}": "Factura Actual",
    "{{importeEnergia}}": "Importe Energ&iacute;a",
    "{{importeTAP}}": "Importe T A P",
    "{{importeAseo}}": "Importe Aseo",
    "{{aplicarEnDeudasPendientes}}": "Aplicar En Deudas Pendientes",
    "{{Interrupciones}}": "Interrupciones",
    "{{alimentador}}": "Alimentador",
    "{{cuchilla}}": "Cuchilla",
    "{{tipoFalla}}": "Tipo Falla",
    "{{numeroInterrupcion}}": "Nro. Int",
    "{{enero}}": "Enero",
    "{{febrero}}": "Febrero",
    "{{marzo}}": "Marzo",
    "{{abril}}": "Abril",
    "{{mayo}}": "Mayo",
    "{{junio}}": "Junio",
    "{{julio}}": "Julio",
    "{{agosto}}": "Agosto",
    "{{septiembre}}": "Septiembre",
    "{{octubre}}": "Octubre",
    "{{noviembre}}": "Noviembre",
    "{{diciembre}}": "Diciembre",
    "{{codMedidor}}": "Cod. Medidor",
    "{{anularCobro}}": "Anular cobro",
    "{{importeTotalDeLaFacturaBs}}": "Importe total de la factura Bs.",
    "{{ajustes}}": "Ajustes",
    "{{codigoAnterior}}": "C&oacute;digo Anterior",
    "{{solicitudServicio}}": "Solicitud Servicio",
    "{{ordenesServicio}}": "Ordenes Servicio",
    "{{lecturas}}": "Lecturas",
    "{{lectura}}": "Lectura",
    "{{deudaPendienteCancelada}}": "Deuda Pendiente Cancelada",
    "{{historicoMedidores}}": "Hist&oacute;rico Medidores",
    "{{datosGenerales}}": "Datos Generales",
    "{{datosTecnicos}}": "Datos T&eacute;cnicos",
    "{{datosLecturaCobranza}}": "Datos Lectura Cobranza",
    "{{correcionDireccion}}": "Correcci&oacute;n de direcci&oacute;n",
    "{{datosActuales}}": "Datos actuales",
    "{{direccionActual}}": "Direcci&oacute;n actual",
    "{{correcionNombre}}": "Correcci&oacute;n de Nombre",
    "{{correcionCelular}}": "Correcci&oacute;n de celular",
    "{{numSerie}}": "# Serie",
    "{{anioCompra}}": "A&ntilde;o de Compra",
    "{{cTap}}": "Costo TAP",
    "{{cEnergia}}": "Costo Energ&iacute;a",
    "{{cAseo}}": "Costo Aseo",
    "{{tipoImpresion}}": "Tipo Impresi&oacute;n",
    "{{contrato}}": "Contrato",
    "{{fechaConexion}}": "Fecha Conexi&oacuten",
    "{{fechaSuspension}}": "Fecha Suspensi&oacute;n",
    "{{depositoGarantia}}": "Deposito Garant&iacute;a",
    "{{zonificacion}}": "Zonificaci&oacute;n",
    "{{revertir}}": "Revertir",
    "{{antigua}}": "Antigua",
    "{{rezonificados}}": "Re-Zonificados",
    "{{rezonificar}}": "Re-Zonificar",
    "{{numeroDigito}}": "N&uacute;mero D&iacute;gito",
    "{{potencia validada}}:": "Pot. Validada",
    "{{potencia fuera punta}}:": "Pot. Fuera Punta",
    "{{modificacionRed}}": "Modificaci&oacute;n de red?",
    "{{constructivo}}": "Constructivo",
    "{{saldo}}": "Saldo",
    "{{saldoBs}}": "Saldo Bs.",
    "{{digitos}}": "D&iacute;gitos",
    "{{horario}}": "Horario",
    "{{reactiva}}": "Reactiva",
    "{{variable}}": "Variable",
    "{{cobroEnBanco}}": "Cobro en banco",
    "{{cobroEnCajasPropias}}": "Cobro en cajas propias",
    "{{gestionDeCheques}}": "Gesti&oacute;n de cheques",
    "{{instalacionesDaniadas}}": "Instalaciones Da&ntilde;adas",
    "{{identificarLaEmpresaOPersonas}}": "Identificar la Empresa o Personas",
    "{{personalDeLaEmpresa}}": "Personal de la Empresa",
    "{{otraPersonaOPersonasAjenas}}": "Otra persona o personas ajenas",
    "{{existieronDescargasAtmosfericasUOtrosFenomenosNaturales}}": "Existieron descargas atmosfericas u otros fenómenos naturales",
    "{{seRegistraronProblemasElectricosEnElDomicilio}}": "Se registraron problemas electricos en el domicilio",
    "{{enLaFechaSenialadaConoceDeUnProblemaSimilarEnSuVecindario}}": "En la fecha Señalada conoce de un problema similar en su vecindario",
    "{{indicarSiSeEncontrabantrabajandoEnElLugarDelHecho}}": "Indicar si se encontraban trabajando en el lugar del hecho",
    "{{documentacion}}": "Documentaci&oacute;n",
    "{{enElLugar}}": "En el lugar",
    "{{aprobarValidez}}": "Aprobar Validez",
    "{{verValidez}}": "Ver Validez",
    "{{ct}}": "Ct's",
    "{{listadoDeCobranzas}}": "Listado de cobranzas",
    "{{cobrosRealizados}}": "Cobros realizados",
    "{{totalCanceladoBs}}": "Total cancelado Bs.",
    "{{totalCobradoBs}}": "Total Cobrado Bs.",
    "{{AnticipoAplicado}}": "Anticipo aplicado",
    "{{id}}": "ID",
    "{{despliegueDeMovimientoDiario}}": "Despliegue de movimiento diario",
    "{{nro.Cupones}}": "Nro. Cupones",
    "{{nro.Recibo}}": "Nro. Recibo",
    "{{recaudacionEntidadesFinancieras}}": "Recaudaci&oacute;n Entidades Financieras",
    "{{totalAgencia}}": "Total Agencia",
    "{{original}}": "Original",
    "{{ajustado}}": "Ajustado",
    "{{noData}}": "No existen datos disponibles",
    "{{agregarMaterial}}": "Agregar material",
    "{{agregarArtefactos}}": "Agregar artefactos",
    "{{badgeDefault}}": "actual 0",
    "{{reImpresionEnBanco}}": "Re-Impresi&oacute;n en banco",
    "{{destino}}": "Destino",
    "{{critica}}": "Cr&iacute;tica",
    "{{noCsgData}}": "No tiene",
    "{{natural}}": "natural",
    "{{tipoConsumidor}}": "Tipo Consumidor",
    "{{grupoLectura}}": "Grupo Lectura",
    "{{buscador}}": "Buscador",
    "{{informes}}": "Informes",
    "{{listaCambioNombre}}": "Lista de cambios de Nombre",
    "{{revisado}}": "Revisado",
    "{{grupoDescripcion}}": "Grupo",
    "{{grupo}}": "Grupo",
    "{{kwh_dev}}": "Kwh/Dev",
    "{{categoriaTarifaEnergia}}": "Categor&iacute;a  Tarifa ",
    "{{categoriaTap}}": "Categor&iacute;a ",
    "{{categoriaAseo}}": "Categor&iacute;a Aseo",
    "{{deuda}}": "Deuda",
    "{{facturaAAfectar}}": "Factura a afectar",
    "{{opcionesExportacion}}": "Opciones de Exportaci&oacute;n",
    "{{ordenLectura}}": "Orden Lectura",
    "{{tipoFacturacion}}": "Tipo Facturaci&oacute;n",
    "{{tiempoTranscurrido}}": "Tiempo Transcurrido",
    "{{procesando}}": "Procesando",
    "{{cliente}}": "Cliente",
    "{{confirmDesistirSolicitud}}": "Esta seguro de desistir la solicitud?",
    "{{Atras}}": "Atras",
    "{{Exportar Archivos}}": "Bajar Archivos",
    "{{desistir}}": "Desistir",
    "{{opcionesReportes}}": "Opciones de Reportes",
    "{{opciones}}": "Opciones",
    "{{consultaMedidores}}": "Consulta Medidores",
    "{{codigoServicio}}": "C&oacute;digo Servicio",
    "{{nro}}": "Nro.",
    "{{activa}}": "Activa",
    "{{Importar Archivos}}": "Subir Archivos",
    "{{csg_tbl_show_marca}}": "Marca",
    "{{csg_tbl_show_paisOrigen}}": "Pa&iacute;s Or&iacute;gen",
    "{{csg_tbl_show_fechaAdquisicion}}": "Fecha Adquisici&oacute;n",
    "{{csg_tbl_show_numeroFabrica}}": "N&uacute;mero F&aacute;brica",
    "{{csg_tbl_show_ultimoIndice}}": "Ultimo Indice",
    "{{csg_tbl_show_numeroFases}}": "N&uacute;mero Fases",
    "{{csg_tbl_show_numeroHilos}}": "N&uacute;mero Hilos",
    "{{csg_tbl_show_numeroElementos}}": "N&uacute;mero Elementos",
    "{{csg_tbl_show_propietario}}": "Propietario",
    "{{csg_tbl_show_conectado}}": "Conectado",
    "{{verDatosMedidor}}": "Ver Datos Medidor",
    "{{cantidadEnergia}}": "Cant. Energia",
    "{{cantidadPotencia}}": "Cant. Potencia",
    "{{cantidadBloques}}": "Cant. Bloques",
    "{{subirArchivos}}": "Subir Archivos",
    "{{noGenera}}": "No Genera",
    "{{condicionConsumidor}}": "Condicion Consumidor",
    "{{programacionCortesYsuspensiones}}": "Programacion de Cortes y Suspensiones",
    "{{retenido}}": "Retenido",
    "{{reImprimirFormOdeco}}": "Re Imprimir Formulario de Reclamaci&oacute;n",
    "{{estadoAsignar}}": "Estado Asignar",
    "{{fase1}}": "Fase 1",
    "{{fase2}}": "Fase 2",
    "{{fase3}}": "Fase 3",
    "{{fase4}}": "Neutro",
    "{{numeroSticker}}": "N&uacute;mero sticker",
    "{{anular}}": "Anular",
    "{{temperaturaEnsayo}}": "Temperatura de ensayo [&deg;C]",
    "{{tensionEnsayo}}": "Tensi&oacute;n de ensayo [V]",
    "{{ensayosCon}}": "Ensayos con",
    "{{fp}}": "F.P.",
    "{{cargaAlta}}": "Carga Alta",
    "{{cargaBaja}}": "Carga Baja",
    "{{cargaInductiva}}": "Carga Inductiva",
    "{{reg}}": "Reg.",
    "{{ss}}": "S.S.",
    "{{os}}": "O.S.",
    "{{lote}}": "Lote",
    "{{anioFabrica}}": "A&ntilde;o de Fabricaci&oacute;n",
    "{{consumoEstimado}}": "Consumo Estimado",
    "{{csg_tbl_show_id}}": "id",
    "{{csg_tbl_show_idConsumidor}}": "idConsumidor",
    "{{csg_tbl_show_mes}}": "Mes",
    "{{csg_tbl_show_anio}}": "A&ntilde;o",
    "{{csg_tbl_show_lecturaActual}}": "Lectura Actual",
    "{{csg_tbl_show_lecturaAnterior}}": "Lectura Anterior",
    "{{csg_tbl_show_consumoActual}}": "Consumo Actual",
    "{{csg_tbl_show_numeroMedidor}}": "N&uacute;mero Medidor",
    "{{csg_tbl_show_ordenTpl}}": "Orden Tpl",
    "{{csg_tbl_show_ordenLectura}}": "Orden Lectura",
    "{{csg_tbl_show_realizoLectura}}": "Realizo Lectura",
    "{{csg_tbl_show_rutaCodigo}}": "Ruta C&oacute;digo",
    "{{csg_tbl_show_rutaDescripcion}}": "Ruta Descripci&oacute;n",
    "{{csg_tbl_show_remesaCodigo}}": "C&oacute;digo Remesa",
    "{{csg_tbl_show_remesaDescripcion}}": "Descripci&oacute;n Remesa",
    "{{csg_tbl_show_areaCodigo}}": "C&oacute;digo Area",
    "{{csg_tbl_show_areaDescripcion}}": "Descripci&oacute;n Area",
    "{{csg_tbl_show_nivelCalidadCodigo}}": "C&oacute;digo Nivel Calidad",
    "{{csg_tbl_show_nivelCalidadDescricion}}": "Descripci&oacute;n Nivel Calidad",
    "{{csg_tbl_show_sistemaCodigo}}": "C&oacute;digo Sistema",
    "{{csg_tbl_show_sistemaDescripcion}}": "Descripci&oacute;n Sistema",
    "{{csg_tbl_show_tipoLecturaCodigo}}": "C&oacute;digo Tipo Lectura",
    "{{csg_tbl_show_tipoLecturaSigla}}": "Sigla Tipo Lectura",
    "{{csg_tbl_show_tipoLecturaDescripcion}}": "Descripci&oacute;n Tipo Lectura",
    "{{csg_tbl_show_multiplicadorCalculado}}": "Multiplicador Calculado",
    "{{csg_tbl_show_tipoMedidor}}": "Tipo Medidor",
    "{{csg_tbl_show_categoriaCodigo}}": "C&oacute;digo Categor&iacute;a",
    "{{csg_tbl_show_categoriaDescripcion}}": "Descripci&oacute;n Categor&iacute;a",
    "{{csg_tbl_show_categoriaSigla}}": "Sigla Categor&iacute;a",
    "{{csg_tbl_trs_}}": "Sigla Categor&iacute;a",
    "{{csg_tbl_trs_decimal}}": "",
    "{{csg_tbl_trs_emptyTable}}": "No hay datos disponibles en esta tabla",
    "{{csg_tbl_trs_info}}": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
    "{{csg_tbl_trs_infoEmpty}}": "Mostrando registros del 0 al 0 de un total de 0 registros",
    "{{csg_tbl_trs_infoFiltered}}": "(filtrado de un total de _MAX_ registros)",
    "{{csg_tbl_trs_infoPostFix}}": "",
    "{{csg_tbl_trs_thousands}}": ",",
    "{{csg_tbl_trs_lengthMenu}}": "Mostrar _MENU_ registros",
    "{{csg_tbl_trs_loadingRecords}}": "Cargando...",
    "{{csg_tbl_trs_processing}}": "Procesando...",
    "{{csg_tbl_trs_search}}": "Buscar:",
    "{{csg_tbl_trs_zeroRecords}}": "No se encontraron resultados",
    "{{csg_tbl_trs_first}}": "Primero",
    "{{csg_tbl_trs_last}}": "Ultimo",
    "{{csg_tbl_trs_next}}": "Siguiente",
    "{{csg_tbl_trs_previous}}": "Anterior",
    "{{csg_tbl_trs_sortAscending}}": ": Activar para ordenar la columna de manera ascendente",
    "{{csg_tbl_trs_sortDescending}}": ": Activar para ordenar la columna de manera descendente",
    "{{error}}": "Error &#37;",
    "{{numRevoPul}}": "N&deg; Rev. o Pulsos",
    "{{valorLimite}}": "Valor Limite",
    "{{valorEncontrado}}": "Valor Encontrado",
    "{{tiempoEnsayo}}": "Tiempo de Ensayo",
    "{{uPercent}}": "&plusmn; U [&#37;]",
    "{{REPONER}}": "REPONER",
    "{{REPARAR}}": "REPARAR",
    "{{codigo_anterior}}": "C&oacute;digo Anterior",
    "{{numero_documento}}": "N&uacute;mero Documento",
    "{{carta_factura}}": "Carta Factura",
    "{{csg_select_todos}}": "Todos",
    "{{csg_select_ninguno}}": "Ninguno",
    "{{csg_search}}": "Ingrese el t&eacute;rmino a buscar (Por defecto se buscar&aacute; s&oacute;lo por c&oacute;digo)",
    "{{csg_nadaSeleccionado}}": "Ninguna selecci&oacute;n",
    "{{csg_tbl_show_modelo}}": "Modelo",
    "{{historicoDelMedidor}}": "hist&oacute;rico Medidor",
    "{{historicoMedidor}}": "Hist&oacute;rico Medidor",
    "{{prescintosMedidor}}": "Precintos Medidor",
    "{{verDetalles}}": "Mostrar Detalles",
    "{{consultaLecturas}}": "Consulta Lecturas",
    "{{detallesLectura}}": "Detalles Lectura",
    "{{cantidadReal}}": "Cantidad real",
    "{{tecnico}}": "Tecnico",
    "{{ninguna}}": "Ninguna",
    "{{pagoACuenta}}": "Pago a cuenta",
    "{{cuenta}}": "Cuenta",
    "{{emision}}": "Emisi&oacute;n",
    "{{adicionales}}": "Adicionales",
    "{{dejado-s}}": "Dejado(s)",
    "{{precinto-s}}": "Precinto(s)",
    "{{responsable}}": "Responsable",
    "{{valores}}": "Valores",
    "{{dejados}}": "Dejados",
    "{{interno}}": "Interno",
    "{{externo}}": "Externo",
    "{{muestraPorciento}}": "Muestra &#37;",
    "{{porcentajeMuestra}}": "Porcentaje P&#47;muestra",
    "{{desconeccion}}": "Desconexi&oacute;n",
    "{{coneccion}}": "Conexi&oacute;n",
    "{{regularizacion}}": "Regularizaci&oacute;n",
    "{{bajar}}": "Bajar Archivo",
    "{{reportes}}": "Reportes",
    "{{rutas}}": "Ruta",
    "{{Transcripcion lecturas PD}}": "Transcripcion lecturas PD",
    "{{Transcripcion lecturas MD}}": "Transcripcion lecturas MD",
    "{{Transcripcion lecturas GD}}": "Transcripcion lecturas GD",
    "{{noMovido}}": "X - No Se Movi&oacute;",
    "{{noEncontrado}}": "N - No Encontrado",
    "{{violado}}": "V - Violado",
    "{{correcto}}": "C - Correcto",
    "{{ruta}}": "Ruta",
    "{{renglon}}": "Rengl&oacute;n",
    "{{semestre}}": "Semestre",
    "{{excluircausa}}": "Excluir causa",
    "{{consideraorigen}}": "Considera origen",
    "{{verDetallesLectura}}": "Ver Detalles",
    "{{descripcionConsumo}}": "Descripci&oacute;n Consumo",
    "{{tipoMedidor}}": "Tipo Medidor",
    "{{ordenTpl}}": "Orden TPL",
    "{{tipoLectura}}": "Tipo Lectura",
    "{{fechaLectura}}": "Fecha Lectura",
    "{{fechaLecturaAnterior}}": "Fecha Lectura Anterior",
    "{{multiplicadorCalculado}}": "Multiplicador",
    "{{calculoindices}}": "Calculo de &Iacute;ndices",
    "{{calculoindicesdetalle}}": "Calculo de &Iacute;ndices Detalle",
    "{{normas}}": "Normas",
    "{{pt}}": "Pt's",
    "{{envio}}": "Envio",
    "{{importePagadoBs}}": "Importe Pagado Bs.",
    "{{cobranzaEnEntidadesFinancieras}}": "Cobranza en Entidades Financieras",
    "{{detalleDeCobro}}": "Detalle de cobro",
    "{{Facturacion Movil}}": "Facturaci&oacute;n M&oacutevil",
    "{{consultaGeneral}}": "Consulta General",
    "{{puntoSuministro}}": "Punto Suministro",
    "{{vanos}}": "Vanos",
    "{{subEstacion}}": "Sub Estaci&oacute;n",
    "{{capacidadInstalada}}": "Capacidad Instalada",
    "{{ramal}}": "Ramal",
    "{{lecturaAnterior}}": "Lectura Anterior",
    "{{consumoActual}}": "Consumo Actual",
    "{{lecturaActual}}": "Lectura Actual",
    "{{consumoPromedio}}": "Consumo Promedio",
    "{{fechaLecturaActual}}": "Fecha Lectura Actual",
    "{{lecturaValidada}}": "Lectura Validada",
    "{{csg_tbl_show_fechaLectura}}": "Fecha Lectura",
    "{{csg_tbl_show_fecha_emision}}": "Fecha Emisi&oacute;n",
    "{{csg_tbl_show_consumo_facturado}}": "Consumo Facturado",
    "{{csg_tbl_show_categoria_sigla}}": "Categor&iacute;a Sigla",
    "{{csg_tbl_show_categoria_descripcion}}": "Categor&iacute;a Descripci&oacute;n",
    "{{csg_tbl_show_tipo_lectura_sigla}}": "LEC",
    "{{csg_tbl_show_tipo_lectura_descripcion}}": "Tipo Lectura Descripci&oacute;n",
    "{{csg_tbl_show_formulario_descripcion}}": "FORM",
    "{{csg_tbl_show_importe_energia}}": "Energ&iacute;a",
    "{{csg_tbl_show_importe_tas}}": "TAS",
    "{{csg_tbl_show_importe_tap}}": "TAP",
    "{{csg_tbl_show_fecha_vencimiento}}": "Fecha Vencimiento",
    "{{csg_tbl_show_numero_factura}}": "N&uacute;mero Factura",
    "{{csg_tbl_show_estado}}": "Estado Deuda",
    "{{consultaDeudaPendienteCancelada}}": "Consulta Deuda Pendiente Cancelada",
    "{{imposibilidadComunicacion}}": "Imposibilidad de Comunicaci&oacute;n",
    "{{diasTranscurridos}}": "Días Transcurridos",
    "{{csg_tbl_show_tipo_categoria}}": "Tipo Categor&iacute;a",
    "{{csg_tbl_show_importe_a_pagar}}": "TOTAL",
    "{{csg_tbl_show_importe}}": "Importe a Pagar",
    "{{deudaPendiente}}": "Deuda Pendiente",
    "{{indiceUltimo}}": "&Iacute;ndice &Uacute;ltimo",
    "{{verificarMedidor}}": "Verificar Medidor",
    "{{infoSolicitud}}": "Info Solicitud",
    "{{infoConsumidor}}": "Info Consumidor",
    "{{verificarBarrio}}": "Verificar Barrio",
    "{{verificarActividad}}": "Verificar Actividad",
    "{{obtenerUbicacion}}": "Obtener Ubicaci&oacute;n",
    "{{agregarArtefacto}}": "Agregar Artefacto",
    "{{duplicarSolicitud}}": "Duplicar solicitud",
    "{{codigoInspeccion}}": "C&oacute;digo inspecci&oacute;n",
    "{{calendarizacion}}": "Calendarizaci&oacute;n",
    "{{feriados}}": "Feriados",
    "{{dias}}": "Dias",
    "{{kwh_adicionales}}": "kWh Adicionales",
    "{{kwh_devolver}}": "kWh Devolver",
    "{{perdidas_trafo}}": "Perdidas Trafo",
    "{{perdidas_linea}}": "Perdidas Linea",
    "{{sectorEspecial}}": "Sector Especial",
    "{{estadoDesde}}": "Estado Desde",
    "{{estadoHasta}}": "Estado Hasta",
    "{{numeroMinDeuda}}": "Numero Minimo Deuda",
    "{{faltanRemesas}}": "Faltan Remesas",
    "{{csg_tbl_show_codigo_solicitud}}": "C&oacute;digo Solicitud",
    "{{csg_tbl_show_tipo_solicitud}}": "Tipo solicitud",
    "{{csg_tbl_show_fecha_registro}}": "Fecha Registro",
    "{{csg_tbl_show_estado_solicitud}}": "Estado Solicitud",
    "{{consultaSolicitud}}": "Consulta Solicitud",
    "{{factor}}": "Factor",
    "{{sectorId}}": "Sector Id",
    "{{idTipoOperador}}": "Id Tipo Operador",
    "{{agregarPrecinto}}": "Agregar Precinto",
    "{{corrientePrimario}}": "Corriente Primario Ip (A) ",
    "{{corrienteSecundario}}": "Corriente Secundario Is (A)",
    "{{modificarSolicitud}}": "Modificar solicitud",
    "{{duplicateSolicitud}}": "Duplicar solicitud",
    "{{exportExcel}}": "Export excel",
    "{{csg_tbl_show_codigo_orden}}": "C&oacute;digo Orden",
    "{{csg_tbl_show_tipo_orden}}": "Tipo Orden",
    "{{csg_tbl_show_estado_orden}}": "Estado Orden",
    "{{csg_tbl_show_fecha_transcripcion}}": "Fecha Transcripci&oacute;n",
    "{{csg_tbl_show_fecha_cumplimiento}}": "Fecha Cumplimiento",
    "{{csg_tbl_show_sector_origen}}": "Sector Origen",
    "{{csg_tbl_show_sector_destino}}": "Sector Destino",
    "{{csg_tbl_show_ruta_codigo}}": "Ruta",
    "{{csg_tbl_show_ruta_descripcion}}": "Ruta Descripci&oacute;n",
    "{{csg_tbl_show_numero_medidor_conexion}}": "Medidor Conexi&oacute;n",
    "{{csg_tbl_show_propiedad_medidor_conexion}}": "Propiedad",
    "{{csg_tbl_show_numero_medidor_desconexion}}": "Medidor Desconexi&oacute;n",
    "{{csg_tbl_show_propiedad_medidor_desconexion}}": "Propiedad",
    "{{csg_tbl_show_asigna_medidor}}": "Asigna Medidor",
    "{{csg_tbl_show_retira_medidor}}": "Retira Medidor",
    "{{consultaOrden}}": "Consulta Orden",
    "{{buscarZona}}": "Buscar zona",
    "{{buscarCartaFactura}}": "Buscar cata factura",
    "{{buscarBarrio}}": "Buscar barrio",
    "{{buscarActividadEconomica}}": "Buscar actividad econ&oacute;mica",
    "{{buscarOperador}}": "Buscar operador",
    "{{buscarLocalidad}}": "Buscar localidad",
    "{{buscarArea}}": "Buscar &aacute;rea",
    "{{csg_tbl_show_codigo_reclamo}}": "C&oacute;digo Reclamo",
    "{{csg_tbl_show_tipo_reclamo}}": "Tipo Reclamo",
    "{{csg_tbl_show_descripcion_reclamo}}": "Descripci&oacute;n",
    "{{csg_tbl_show_estado_reclamo}}": "Estado Reclamo",
    "{{csg_tbl_show_fecha_pronunciamiento}}": "Fecha Pronunciamiento",
    "{{csg_tbl_show_motivo}}": "Motivo",
    "{{csg_tbl_show_cre_fiscal}}": "Cr&eacute;dito Fiscal",
    "{{csg_tbl_show_cre_energia}}": "Cr&eacute;dito Energ&iacute;a",
    "{{csg_tbl_show_cre_tap}}": "Cr&eacute;dito TAP",
    "{{csg_tbl_show_cre_aseo}}": "Cr&eacute;dito TAS",
    "{{csg_tbl_show_deb_fiscal}}": "D&eacute;bito Fiscal",
    "{{csg_tbl_show_deb_energia}}": "D&eacute;bito Energ&iacute;a",
    "{{csg_tbl_show_deb_tap}}": "D&eacute;bito TAP",
    "{{csg_tbl_show_deb_aseo}}": "D&eacute;bito TAS",
    "{{csg_tbl_show_aplica_deuda}}": "Aplica Deuda",
    "{{consultaReclamo}}": "Consulta Reclamo",
    "{{nominal}}": "Nominal",
    "{{nombre_razonSolcial}}": "Nombre/Razon social",
    "{{CI_NIT}}": "CI/NIT",
    "{{numeroInspeccion}}": "N&uacute;mero inspecci&oacute;n",
    "{{consultaAjuste}}": "Consulta Ajuste",
    "{{deudaCanceladaDia}}": "Deuda Cancelada D&iacute;a",
    "{{detallesConsumoFacturado}}": "Detalles Consumo Facturado",
    "{{consumoFacturado}}": "Consumo Facturado",
    "{{csgMultiplicador}}": "Multiplicador",
    "{{historicoDeudaPendienteCancelada}}": "Hist&oacute;rico Deuda Pendiente Cancelada",
    "{{deudaCancelada}}": "Deuda Cancelada",
    "{{descripcionDocumento}}": "Descripci&oacute;n Documento",
    "{{haContestado}}": "Ha Contestado"

};
var en = {
};
